version: '3'
services:
    nginx:
        image: yappabe/nginx:1.9
        restart: always
        volumes:
            - .:/var/www/app
        links:
            - php
        depends_on:
            - php
        environment:
            DOCUMENT_ROOT: /var/www/app/web
            INDEX_FILE: index.php
            PHP_FPM_SOCKET: php:9000
            VIRTUAL_HOST: api.sourcebox.be
            LETSENCRYPT_HOST: api.sourcebox.be
            LETSENCRYPT_EMAIL: admin@sourcebox.be

    php:
        image: yappabe/php:7.2
        restart: always
        volumes:
            - ./:/var/www/app
        working_dir: /var/www/app
        environment:
            PHP_FPM_USER: root
        links:
            - redis
        depends_on:
            - redis

    redis:
        image: redis:latest

networks:
    default:
       external:
         name: webproxy
